<?php

return [
    "APP_NAME" => "Fittoss Wellness India Private Limited",
    'COMPANY_NAME' => "Fittoss Wellness India Pvt. Ltd.",
    'FSSAI_LICENSE_NO' => 10251119107963543,
    'CIN_NUMBER' => "U70200GJ2024PTC148223",
    'GST_NUMBER' => "24AAFCF7984E1ZF",
    'COMPANY_MOBILE' => "8140390170",
    'COMPANY_INFO_EMAIL' =>  "info@fittoss.com",
    'COMPANY_HR_EMAIL' =>  "info@fittoss.com",
    'COMPANY_ADDRESS' => "246, Unique Square,<br/>Singanpore Shubham K Mart,<br/> Katargam,Surat - 395004,<br/>Gujarat,India ",
    'COMPANY_ADDRESS_INVOICE' => "246, Unique Square,Singanpore Shubham K Mart, Katargam,<br/>Surat - 395004,Gujarat,India ",

    'PARTNER_PORTAL_URL' => "https://partner.fittoss.com",

    'MANAGE_PANEL_PRODUCT_IMAGE_PATH' => env('MANAGE_PANEL_PRODUCT_IMAGE_PATH'),
    'GEOLOCATION_API_KEY' => env('GEOLOCATION_API_KEY'),

    'COMPANY_FACEBOOK' => "https://www.facebook.com/fittoss",
    'COMPANY_INSTAGRAM' => "https://www.instagram.com/fittossapp/",
    'COMPANY_TWITTER' => "https://x.com/fittossofficial",
    'COMPANY_LINKEDIN' => "https://www.linkedin.com/company/fittoss",
    'COMPANY_PINTEREST' => "https://in.pinterest.com/fittossofficial",
    'COMPANY_YOUTUBE' => "https://www.youtube.com/@fittoss.official",

    'UAT_MOBILE_NUMBERS' => ['8530537178', '8511127147', '7283934596', '9904466599', '6358265371', '6358141352'],
    'ADMIN_MOBILE_NUMBERS' => ['9023987358', '9998846739', '6358141826', '6358265371', '9265265518', '6358141352', '7486083302', '9998807547', '9409665995'],

    'WEIGHT_LOSS_PROGRAM_ID' => 1,
    'WEIGHT_LOSS_WEBINAR_ID' => 9,
    'BODYFAT_ANALYSIS_WORKSHOP_ID' => 10,
    'HEALTH_AWARENESS_WORKSHOP_ID' => 11,
    "AFFILIATE_PARTNERSHIP_PROGRAM_PRODUCT_ID" => 12,
    "HEALTH_COACH_WEBINAR_PRODUCT_ID" => 13,
    "BUSINESS_OPPORTUNITY_WORKSHOP_PRODUCT_ID" => 14,
    "FITONE_OFFER_ID" => 15,
    "EXPERT_CONSULTATION_OFFER_ID" => 16,
    "MEMBERSHIP_PLAN_OFFER_ID" => 17,
    "ASSOCIATE_PARTNER_PROGRAM_OFFER_ID" => 18,
    "ADVANCE_PLAN_OFFER_ID" => 19,
    "ONBOARD_UPI_PAYMENT_OFFER_ID" => 20,
    'EXPERT_CONSULTATION_PLAN_ID' => 21,
    'HEALTH_CONSULTATION_PLAN_ID' => 22,
    'WEIGHT_LOSS_OFFER_ID' => 23,
    'ULTIMATE_PROGRAM_ID' => 24,
    'CUSTOMIZE_PROGRAM_ID' => 25,
    'WEIGHT_LOSS_WEBINAR_OFFER_ID' => 26,

    # Interakt template names
    "WEIGHT_LOSS_PROGRAM_SUCCESS_TEMPLATE_NAME" => 'weightlossprogram_pay_success',
    "WEIGHT_LOSS_PROGRAM_FAIL_TEMPLATE_NAME" => 'weightlossprogram_pay_fail',
    "WEIGHT_LOSS_WEBINAR_SUCCESS_TEMPLATE_NAME" => '',
    "WEIGHT_LOSS_WEBINAR_FAIL_TEMPLATE_NAME" => '',

    "WEIGHT_LOSS_OFFER_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "WEIGHT_LOSS_OFFER_FAIL_TEMPLATE_NAME" => 'crash_offer_fail_2',
    "ULTIMATE_PROGRAM_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "ULTIMATE_PROGRAM_FAIL_TEMPLATE_NAME" => 'ultimate_offer_fail_1',
    "CUSTOMIZE_PROGRAM_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "CUSTOMIZE_PROGRAM_FAIL_TEMPLATE_NAME" => 'customised_offer_fail_2',
    "WEIGHT_LOSS_WEBINAR_OFFER_SUCCESS_TEMPLATE_NAME" => '',
    "WEIGHT_LOSS_WEBINAR_OFFER_FAIL_TEMPLATE_NAME" => '',
    "FITONE_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "FITONE_FAIL_TEMPLATE_NAME" => 'fitone_offer_fail_',
    "EXPERT_CONSULTATION_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "EXPERT_CONSULTATION_FAIL_TEMPLATE_NAME" => 'expert_offer_fail',
    "MEMBERSHIP_PLAN_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "MEMBERSHIP_PLAN_FAIL_TEMPLATE_NAME" => 'membership_plan_fail',
    "ASSOCIATE_PARTNER_PROGRAM_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "ASSOCIATE_PARTNER_PROGRAM_FAIL_TEMPLATE_NAME" => 'associate_partners_fail',
    "ADVANCE_PLAN_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "ADVANCE_PLAN_FAIL_TEMPLATE_NAME" => 'advance_plan_fail',
    "ONBOARD_UPI_PAYMENT_SUCCESS_TEMPLATE_NAME" => 'all_offer_pay_done',
    "ONBOARD_UPI_PAYMENT_FAIL_TEMPLATE_NAME" => 'onboard_pay_offer_fail_2',

    "EXPERT_CONSULTATION_PLAN_SUCCESS_TEMPLATE_NAME" => '',
    "EXPERT_CONSULTATION_PLAN_FAIL_TEMPLATE_NAME" => '',
    "HEALTH_COACH_WEBINAR_SUCCESS_TEMPLATE_NAME" => '',
    "HEALTH_COACH_WEBINAR_FAIL_TEMPLATE_NAME" => '',
];
